export const CaraousalData = [
    {
        id: 1,
        title: "Oppenheimer",
        URL: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        imgLogo: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        imgThumbnail: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        genre: "Action",
        trailer: "Trailer",
        video: "Video",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr", "chris hemsworth", "mark ruffalo"],
        writer: [ "Rober downey jr", "chris hemsworth", "mark ruffalo"],
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021",
        isSeries: false,
        isTrending: true,
        isPopular: true,
        isTopRated: true,
        isRecommended: true,
    },
    {
        id: 2,
        title: "Avengers Endgame",
        URL: "/Cinemora/Images/Movies/Endgame.jpg",
        type: "movies",
        Ratings: "5.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 3,
        title: "Inception",
        URL: "/Cinemora/Images/Movies/Inception.jpg",
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 4,
        title: "Interstellar",
        URL: "/Cinemora/Images/Movies/Interstellar.jpg",
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 5,
        title: "Tenet",
        URL: "/Cinemora/Images/Movies/Tenet.jpg",
        type: "movies",
        Ratings: "4.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 6,
        title: "Peaky Blinders",
        URL: "/Cinemora/Images/Movies/Peaky Blinders.jpg",
        type: "series",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
]