export const CaraousalData = [
    {
        id: 1,
        title: "Oppenheimer",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.", 
        URL: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        imgLogo: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        imgThumbnail: "/Cinemora/Images/Movies/Oppenheimer.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Oppenheimer.mp4",
        video: "Video",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr ",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr ",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr ",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr ",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        writer: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021",
        isSeries: false,
        isTrending: true,
        isPopular: true,
        isTopRated: true,
        isRecommended: true,
    },
    {
        id: 2,
        title: "Avengers Endgame",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.",
        URL: "/Cinemora/Images/Movies/Endgame.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Endgame.mp4",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr " , " chris hemsworth " , " mark ruffalo "],
        writer: [ "Rober downey jr " , " chris hemsworth " , " mark ruffalo "],
        type: "movies",
        Ratings: "5.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 3,
        title: "Inception",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.",
        URL: "/Cinemora/Images/Movies/Inception.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Inception.mp4",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr ", " chris hemsworth ", " mark ruffalo "],
        writer: [ "Rober downey jr ", " chris hemsworth ", " mark ruffalo "],
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 4,
        title: "Interstellar",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.",
        URL: "/Cinemora/Images/Movies/Interstellar.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Interstellar.mp4",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        writer: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        type: "movies",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 5,
        title: "Tenet",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.",
        URL: "/Cinemora/Images/Movies/Tenet.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Tenet.mp4",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        writer: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        type: "movies",
        Ratings: "4.6",
        Date: "Dec 28, 2021", 
    },
    {
        id: 6,
        title: "Peaky Blinders",
        subtitle: "Lorem ipsum dolor sit amet",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sit atque veniam sint explicabo? Nisi, dolores amet culpa voluptatum voluptatem saepe voluptatibus ab dolorem possimus quas, et, animi magnam error.",
        URL: "/Cinemora/Images/Movies/Peaky Blinders.jpg",
        genre: "Action",
        trailer: "/Cinemora/Trailer/Peaky.mp4",
        cast:[
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
            {
                pfp: "/Cinemora/Images/Profile.jpg",
                name: "Rober downey jr",
            },
        ],
        duration: "2h 10m",
        director: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        writer: [ "Rober downey jr ", "chris hemsworth ", "mark ruffalo "],
        type: "series",
        Ratings: "7.6",
        Date: "Dec 28, 2021", 
    },
]